# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build with Maven
      run: mvn -B spring-boot:build-image --file pom.xml
    - name: Login GitHub Packages
      run: docker login -u ${{ github.actor }} -p ${{ secrets.ACTIONS }} docker.pkg.github.com
    - name: Update docker tag 
      run: docker tag docker:0.0.1-SNAPSHOT docker.pkg.github.com/yookoo/docker/docker:0.0.1-SNAPSHOT
    - name: Push to GitHub Packages
      run: docker push docker.pkg.github.com/yookoo/docker/docker:0.0.1-SNAPSHOT
      
      
